version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ls && ls src && ls src/css
            - run: stat src/css/index.sass
            - run: stat src/css/Index.sass
            - run: npm install
            - run: npx webpack --mode production
            - run: npx sass src/css/Index.sass docs/index.css
            - run: python sheets.py
            - run: node japanese.js
workflows:
    build:
      jobs:
        - build