version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --only=dev
            - run: git config --global user.name "circleci"
            - run: python3 sheets.py
            - run: npx webpack --mode production
            - run: npx sass src/css/Index.sass docs/index.css
            - run: npx gh-pages -m 'auto commit [ci skip]' -d docs

workflows:
    build:
      jobs:
        - build
