name: Deploy to github pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PRIVATE_ASSETS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: python sheets.py
      - run: npm run build
      - run: cp build/index.html build/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
